// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:localsend_app/rust/frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `send_action`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `QsDeviceInfo`, `QsState`, `QsTransferMessage`, `Visibility`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`, `from`

/// Quick Share 서비스를 생성한다.
/// visibility: 0=Visible, 1=Invisible
/// download_path: 수신 파일 저장 경로 (None이면 기본 다운로드 폴더)
void qsCreateService({required int visibility, String? downloadPath}) =>
    RustLib.instance.api.crateApiQuickShareQsCreateService(
      visibility: visibility,
      downloadPath: downloadPath,
    );

/// Quick Share 서버를 시작한다 (mDNS 광고 + TCP 리스너).
/// qs_create_service()가 먼저 호출되어야 한다.
Future<void> qsStartService() =>
    RustLib.instance.api.crateApiQuickShareQsStartService();

/// Quick Share 서비스를 중지한다. 백그라운드 태스크들을 모두 정리한다.
Future<void> qsStopService() =>
    RustLib.instance.api.crateApiQuickShareQsStopService();

/// Quick Share 가시성을 변경한다.
/// visibility: 0=Visible, 1=Invisible, 2=Temporarily (60초 후 Invisible로 전환)
void qsChangeVisibility({required int visibility}) => RustLib.instance.api
    .crateApiQuickShareQsChangeVisibility(visibility: visibility);

/// Quick Share 기기 검색을 시작하고 발견된 기기들을 Dart Stream으로 전달한다.
/// 각 기기는 JSON 문자열로 직렬화되어 전송된다.
/// Dart 측에서 `jsonDecode`로 파싱하여 사용한다.
Stream<String> qsStartDiscovery() =>
    RustLib.instance.api.crateApiQuickShareQsStartDiscovery();

/// Quick Share 전송 상태 (ChannelMessage)를 Dart Stream으로 전달한다.
/// LibToFront 방향의 메시지만 필터링하며, JSON 문자열로 전송된다.
Stream<String> qsStartChannelListener() =>
    RustLib.instance.api.crateApiQuickShareQsStartChannelListener();

void qsAcceptTransfer({required String id}) =>
    RustLib.instance.api.crateApiQuickShareQsAcceptTransfer(id: id);

void qsRejectTransfer({required String id}) =>
    RustLib.instance.api.crateApiQuickShareQsRejectTransfer(id: id);

void qsCancelTransfer({required String id}) =>
    RustLib.instance.api.crateApiQuickShareQsCancelTransfer(id: id);

/// Quick Share 프로토콜로 파일을 전송한다.
/// `ip`, `port`: 상대방 기기의 주소
/// `name`: 상대방 기기의 이름
/// `files`: 전송할 파일 경로 목록
Future<void> qsSendFiles({
  required String ip,
  required int port,
  required String name,
  required List<String> files,
}) => RustLib.instance.api.crateApiQuickShareQsSendFiles(
  ip: ip,
  port: port,
  name: name,
  files: files,
);

/// Quick Share 서비스가 생성되었는지 확인한다.
bool qsIsServiceCreated() =>
    RustLib.instance.api.crateApiQuickShareQsIsServiceCreated();

/// Quick Share 서비스가 시작되었는지 (run() 호출 여부) 확인한다.
bool qsIsServiceRunning() =>
    RustLib.instance.api.crateApiQuickShareQsIsServiceRunning();
